### ISSUE TITLE
TurtleBot Waffle PI not moving

### ISSUE THREAD

**Issue by florianspy** [ROBOTIS-GIT/turtlebot3_applications#20] opened 2018-06-04 12:06 UTC
After starting the commands:
roslaunch turtlebot3_bringup turtlebot3_rpicamera.launch [Turtlebot]

roslaunch turtlebot3_panorama panorama.launch [Remote]
rosservice call turtlebot3_panorama/take_pano 0 360.0 30.0 0.3 [Remote]
Only the following commands are shown in terminal:
[ INFO] [1528113614.391267503]: Degrees to go: 360
[ INFO] [1528113614.391356133]: rotate
[ INFO] [1528113614.491229042]: rotate
[ INFO] [1528113614.591234680]: rotate
[ INFO] [1528113614.691244960]: rotate
[ INFO] [1528113614.791200727]: rotate
[ INFO] [1528113614.891235382]: rotate
[ INFO] [1528113614.991248516]: rotate
[ INFO] [1528113615.091162402]: rotate
[ INFO] [1528113615.191176301]: rotate
[ INFO] [1528113615.291207926]: rotate
[ INFO] [1528113615.391169771]: rotate
but turtlebot3 Waffle PI is not moving at all.

Even after sending 
rosservice call turtlebot3_panorama/take_pano 2 360.0 30.0 0.3 [Remote]
I cannot see any camera picture as shown in the below screenshot.
![grafik](https://user-images.githubusercontent.com/39183098/40916502-36f433cc-6800-11e8-8308-f05d58c40200.png)

When i click on Camera/rgb/image_raw in rqt_image_view i get the images of the camera, so the pi camera should work.

Edit:
i guess the command
roslaunch turtlebot3_bringup turtlebot3_robot.launch [Turtlebot]
has to be launched in advance as well after that the robot starts spinning when 
rosservice call turtlebot3_panorama/take_pano 0 360.0 30.0 0.3 [Remote] 
gets called

Now the turtlebot is spinning around but after it finished one round it get the following error
in the terminal which runs roslaunch turtlebot3_panorama panorama.launch:
[ INFO] [1528123708.812500594]: snap
[ INFO] [1528123709.812693421]: Stiching 2 images
[ INFO] [1528123709.891097584]: Finished Stiching
[ERROR] [1528123709.891145396]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: bgr8).
OpenCV Error: Unknown error code -10 (Raw image encoder error: Empty JPEG image (DNL not supported)) in throwOnEror, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgcodecs/src/grfmt_base.cpp, line 140
[ERROR] [1528123709.891331341]: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgcodecs/src/grfmt_base.cpp:140: error: (-10) Raw image encoder error: Empty JPEG image (DNL not supported) in function throwOnEror
[ERROR] [1528123709.891373088]: [theora] Failed to create encoding context

This error seems to occur when the following command is run during image acquisition
rqt_image_view image:=/turtlebot3_panorama/panorama
and seems to be related to the issue of two instances accessing the same jpeg file

In all cases the panorama image remains grey (see below) when looking at it via
rqt_image_view image:=/turtlebot3_panorama/panorama
![grafik](https://user-images.githubusercontent.com/39183098/40924138-d6d10576-6816-11e8-8fd6-7b8a87ba69f5.png)

even so i get the message in the terminal which runs roslaunch turtlebot3_panorama panorama.launch
[ INFO] [1528123914.836793089]: Stiching 7 images
[ INFO:0] Initialize OpenCL runtime...
[ INFO] [1528123915.545787520]: Finished Stiching
[ INFO] [1528123915.546026709]: Publishing Completed Panorama

**Comment by routiful** [comment] 2018-06-05 08:27
Hi :)

I tested it and get below information in terminal and image

```
[ INFO] [1528186673.507284245]: Stiching 12 images
[ INFO:0] Initialize OpenCL runtime...
[ INFO:0] Successfully initialized OpenCL cache directory: /home/darby/.cache/opencv/3.3.1-dev/opencl_cache/
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_970M--375_66
[ INFO] [1528186674.486975693]: Finished Stiching
[ INFO] [1528186674.487486044]: Publishing Completed Panorama
[ INFO] [1528186674.487518750]: Angle: 6.291084
[ INFO] [1528186674.487536742]: Last Angle: 5.920647
```
Have you installed graphic driver properly? if not, please check it.

And try to use `rqt_image_view` not `rqt_image_view image:=/turtlebot3_panorama/panorama`

Thanks
Darby

**Comment by florianspy** [comment] 2018-06-05 13:02
My terminal generates the following output
encoding: bgr8
is_bigendian: 
[ INFO] [1528203564.997826581]: Stiching 12 images
[ INFO:0] Initialize OpenCL runtime...
[ INFO] [1528203567.362583864]: Finished Stiching
[ INFO] [1528203567.362639221]: Publishing Completed Panorama
[ INFO] [1528203567.362655736]: Angle: 6.317739
[ INFO] [1528203567.362664930]: Last Angle: 5.889652

And starting rqt_image_view i get the picture as shown below (for the camera)
![grafik](https://user-images.githubusercontent.com/39183098/40977441-4436bdd0-68d1-11e8-9630-fd170caeadb1.png)

But when i select /turtlebot3_panorama/panorama still i get the grey image as shown below
![grafik](https://user-images.githubusercontent.com/39183098/40977505-7089486c-68d1-11e8-987c-4bb8c192bbe3.png)

**Comment by routiful** [comment] 2018-06-07 01:12
The `panorama` msg is goint to publish when it is finished stiching.

For example,

```
encoding: bgr8
is_bigendian:
[ INFO] [1528203564.997826581]: Stiching 12 images
[ INFO:0] Initialize OpenCL runtime...
[ INFO] [1528203567.362583864]: Finished Stiching
[ INFO] [1528203567.362639221]: Publishing Completed Panorama **HERE!**
[ INFO] [1528203567.362655736]: Angle: 6.317739
[ INFO] [1528203567.362664930]: Last Angle: 5.889652
```

So, you are supposed to open rqt_image_view before it is finished

**Comment by florianspy** [comment] 2018-06-07 07:38
Great now it works as expected thank you alot for your help

**Comment by routiful** [comment] 2018-06-14 08:23
Hi :)

Panorama example is depend on OpenCV library.
I debugged turtlebot3_panorama node. But I couldn't find any problems.

So I tried more bigger angle to get stitched pano img. Then, I got almost 360 degree image.
For example, 
```
$ rosservice call turtlebot3_panorama/take_pano 0 420.0 30.0 0.3
```
I assume this is caused by algorithm in OpenCV. I will look into this later.

Thanks

**Comment by florianspy** [comment] 2018-06-14 08:41
I tried your command but now i get a blank picture in rqt_image_view again and the following output in the terminal where i am running rqt_image_view

[ERROR] [1528965654.481582318]: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgcodecs/src/loadsave.cpp:711: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_

[ERROR] [1528965657.476861379]: Tried to advertise a service that is already advertised in this node [/rqt_gui_cpp_node_7366/compressed/set_parameters]
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in imdecode_, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgcodecs/src/loadsave.cpp, line 711
[ERROR] [1528965661.494552942]: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgcodecs/src/loadsave.cpp:711: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_

**Comment by routiful** [comment] 2018-06-15 01:13
Thank you for your digging stuff :)

I tested panorama node following you commented.

First, the stitched image is published after last snap. You can check it in [panorama.cpp](https://github.com/ROBOTIS-GIT/turtlebot3_applications/blob/master/turtlebot3_panorama/src/panorama.cpp#L124)
Second, Therefore, You have to open rqt_image_view before last snap.
Third, Although I didn't re-open panorama launch file, I can start another process using _rosservice_
Fourth, I can get a 360 degree image to use below commands

 ```
$ rosservice call turtlebot3_panorama/take_pano 0 420.0 30.0 0.3 
```

The OpenCV Error as you shown is caused by different development environments between you and me. Which do you used graphic card in your PC?

**Comment by florianspy** [comment] 2018-06-15 05:53
Thank you alot for your reply.
This is the graphic card i use:
lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 745] (rev a2)
And this is the opencv version i use:
libopencv-video2.4v5:amd64                   2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Video analysis library

One additional remark:even so turtlebot3_panorama/take_pano 0 360.0 30.0 0.3 was run sometimes only 6 pictures get stiched shouldn't it always be 12?

**Comment by routiful** [comment] 2018-06-18 00:57
Thanks you for your information.
I will search similar problems and how to work panorama library in OpenCV.
Moreover, how about ask your question to [ROS Answer](https://answers.ros.org/questions/)? It might be  get more quickly responses what you want.

**Comment by robotpilot** [comment] 2018-06-24 23:15
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.

**Closed by robotpilot** 2018-06-24 23:15 UTC
Labels: question, waiting for reply
